### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by AngelOfCreation** [GearsDatapacks/mcanim#1]
I summoned an item display with /summon item_display ~ ~ ~ {item:{id:"minecraft:diamond_sword",Count:1b}}.
Then I ran /data modify storage mcanim:api/display_animations/generic animation set value {duration:23,transformation:{scale:[1,2,3],translation:[1,2,3]}}
Finally I ran /execute as @e[type=minecraft:item_display] run function mcanim:api/display_animations/generic

Absolutely nothing happened.
Version 1.19.4.

**Comment by GearsDatapacks** [comment]
You got the storage and function names wrong. it's "display_animation", not "display_animations"

**Comment by AngelOfCreation** [comment]
Man, I got that command from YOUR [modrinth page](https://modrinth.com/datapack/mcanim). This one's on you.
